### ISSUE TITLE
Add image for body

### ISSUE THREAD

**Issue by binarykittenDE** [binarykittenDE/whatTattooNext#4]

**Comment by adsingh14** [comment]
Is using free stock image okay ?

**Comment by adsingh14** [comment]
Using free stock image is okay to you **or** you've some image to showcase there ?

**Comment by adsingh14** [comment]
Using free stock image is okay to you **or** you've some images to showcase there ?

**Comment by adsingh14** [comment]
@binarykittenDE Oops ! I didn't get notification. I've added a temporary image. :neutral_face: 

Please check this commit for background: https://github.com/binarykittenDE/whatTattooNext/commit/1619077eef8b98566da446061a473b9d1ec2f0ec
